filebeat.inputs:
  - type: filestream
    id: spring-boot-json
    enabled: true
    paths:
      - /logs/*/*.json     # All microservices JSON logs
    json.keys_under_root: true
    json.add_error_key: true
    json.overwrite_keys: true
    fields:
      source: spring-boot
    fields_under_root: true

processors:
  - add_host_metadata: ~
  - add_docker_metadata: ~

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.kibana:
  host: "http://kibana:5601"