server:
  port: 8080

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          #uri: http://localhost:9192
          predicates:
            - Path=/order/**
          filters:
            - AuthenticationFilter
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          #uri: http://localhost:9191
          predicates:
            - Path=/payment/**
          filters:
            - AuthenticationFilter
        - id: security-service
          uri: lb://SECURITY-SERVICE
          #uri: http://localhost:8089
          predicates:
            - Path=/auth/**

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

logging:
  file:
    name: logs/microservices.log