server:
  port: 8080

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      # -------------------------
      # Global Filters for all routes
      # -------------------------
      default-filters:
        - AuthenticationFilter
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 10
            redis-rate-limiter.burstCapacity: 20
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
          filters:
            - name: CircuitBreaker
              args:
                name: orderServiceCB
                fallbackUri: forward:/fallback/order
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
          filters:
            - name: CircuitBreaker
              args:
                name: paymentServiceCB
                fallbackUri: forward:/fallback/payment
        - id: security-service
          uri: lb://SECURITY-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: securityServiceCB
                fallbackUri: forward:/fallback/security

# -------------------------
# Management / Actuator
# -------------------------
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

# -------------------------
# Resilience4J
# -------------------------
resilience4j:
  circuitbreaker:
    instances:
      orderServiceCB:
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        slidingWindowSize: 10
        waitDurationInOpenState: 10s

      paymentServiceCB:
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        slidingWindowSize: 10
        waitDurationInOpenState: 10s

      securityServiceCB:
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        slidingWindowSize: 10
        waitDurationInOpenState: 10s


# -------------------------
# Logging
# -------------------------
logging:
  file:
    name: logs/microservices.log
  level:
    org.springframework.cloud.gateway: DEBUG  # Optional: debug gateway routing