spring:
  application:
    name: security-service

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

logging:
  file:
    name: logs/microservices.log