spring:
  application:
    name: security-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:9196}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

# -------------------------
# Logging
# -------------------------
logging:
  file:
    path: ./logs