spring:
  application:
    name: SECURITY-SERVICE

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  file:
    name: logs/microservices.log