server:
    port: 9196

spring:
    application:
        name: config-server
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/mohitsoniji22/config-server

eureka:
    client:
        serviceUrl:
            defaultZone: http://service-registry:8761/eureka/
        register-with-eureka: true
        fetch-registry: true

management:
    endpoints:
        web:
            exposure:
                include: health
    endpoint:
        health:
            show-details: always

logging:
    file:
        name: logs/microservices.log